import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SubNavbar from "@/components/SubNavbar";
import Footer from "@/components/Footer";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} font-sans antialiased`}>
        {/* <body className={`${rubik.className} font-sans antialiased`}> */}

        <div className="w-full flex flex-col">
          <div className="fixed top-0 left-0 w-full z-50">
            <div className="hidden sm:block bg-white shadow">
              <SubNavbar />
            </div>
            <div className="bg-white">
              <Navbar />
            </div>
          </div>
          <main className="pt-[72px] sm:pt-[108px]">{children}</main>
          <div className="w-full">
            <Footer />
          </div>
        </div>
      </body>
    </html >
  );
}
