import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SubNavbar from "@/components/SubNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {children} */}

        {/* <div className="w-full flex flex-col">
          <div className="hidden sm:block">
            <SubNavbar />
          </div>
          <Navbar />
          {children}
        </div> */}

        <div className="w-full flex flex-col">
          {/* Fixed Navbar Container */}
          <div className="fixed top-0 left-0 w-full z-50">
            <div className="hidden sm:block bg-white shadow">
              <SubNavbar />
            </div>
            <div className="bg-white shadow">
              <Navbar />
            </div>
          </div>

          {/* Content - add padding top to prevent nav overlap */}
          <main className="pt-[112px] sm:pt-[108px]">
            {children}
          </main>
        </div>

      </body>
    </html>
  );
}
