export const outlets = [
  {
    title: "ARENA Vipul Motors Faridabad, Mathura Road",
    type: "Showroom",
    address: "27/5 KM, NH-19, Faridabad, Haryana 121002",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Faridabad",
  },
  {
    title: "ARENA Vipul Motors Faridabad, Ballabgarh",
    type: "Showroom",
    address: "Shwar Bhawan, 21/3, Mathura Rd, Industrial Area, Sector 4, Ballabhgarh, Faridabad, Haryana 121004",
    workingHours: "9:00 AM - 7:30 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Faridabad",
  },
  {
    title: "ARENA Vipul Motors, Gurgaon, Udyog Vihar Phase 3",
    type: "Showroom",
    address: "Plot No 504, Plot No 504, Udyog Vihar Phase III, Phase III, Udyog Vihar, Sector 20, Gurugram, Haryana 122001",
    workingHours: "8:00 AM - 6:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Gurugram",
  },
  {
    title: "ARENA Vipul Motors, Noida, Sector 63",
    type: "Showroom",
    address: "Plot No- H, 163, H Block, Sector 63, Noida, Uttar Pradesh 201301",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Noida",
  },
  {
    title: "ARENA Vipul Motors, Noida, Sector 18",
    type: "Showroom",
    address: "P6, Ocean Complex, P Block, Pocket A, Sector 18, Noida, Uttar Pradesh 201301",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Noida",
  },
  {
    title: "ARENA Motors, Gaur City, Noida",
    type: "Showroom",
    address: "Ground Floor 1, Aarza Square, Greater Noida W Rd, Gaur City 1, Sector 4, Noida, Ghaziabad, Uttar Pradesh 201305",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Noida",
  },
  {
    title: "ARENA Vipul Motors, New Delhi, Paschim Vihar",
    type: "Showroom",
    address: "A-4, Shubham Enclave, Reserve Bank Enclave, Paschim Vihar, New Delhi, Delhi, 110063",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "New Delhi",
  },
  {
    title: "ARENA Vipul Motors,Shyam Nagar",
    type: "Showroom",
    address: "S-10, Ajmer Rd, Shyam Nagar, Jaipur, Rajasthan 302019",
    workingHours: "9:00 AM - 7:30 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Jaipur",
  },
  {
    title: "ARENA Vipul Motors, Jaipur Tonk Road",
    type: "Showroom",
    address: "Shop No G-1 & G-2, Jaipur Center, B2 Byepass Road, Tonk Rd, near First Cinema, Jaipur, Rajasthan 302020",
    workingHours: "8:00 AM - 6:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Jaipur",
  },
  {
    title: "ARENA Vipul Motors Dausa",
    type: "Showroom",
    address: "Agra - Jaipur Rd, Vinayak Nagar, Dausa, Rajasthan 303303",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Dausa",
  },
  {
    title: "NEXA Vipul Motors, Delhi, Gokulpuri",
    type: "Showroom",
    address: "D, 3, Wazirabad Rd, West Jyoti Nagar, Ashok Nagar, Shahdara, Delhi, 110093",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "New Delhi",
  },
  {
    title: "NEXA Vipul Motors, Noida, Sector 63",
    type: "Showroom",
    address: "Plot No- H, 153, Sector 63 Rd, H Block, Sector 63, Noida, Uttar Pradesh 201301",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Noida",
  },
  {
    title: "NEXA Vipul Motors, NIT Central Faridabad Bata Chowk",
    type: "Showroom",
    address: "Bata Chowk, Industrial Plot No 34, Sub Division No-3, New Industrial Township, Faridabad, Haryana 121001",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Faridabad",
  },
  {
    title: "NEXA Vipul Motors Ballabgarh",
    type: "Showroom",
    address: "Om Sai Tower, Plot 12/A, NH-19, opposite JCB India, Sanjay Colony, Ballabhgarh, Faridabad, Haryana 121004",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Faridabad",
  },
  {
    title: "NEXA Vipul Motors, Gurugram, Udyog Vihar Phase 3",
    type: "Showroom",
    address: "Plot No A504 Phase III, Udyog Vihar, Sector 20, Gurugram, Haryana 122001",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Gurugram",
  },
  {
    title: "NEXA Vipul Motors, Jaipur, Ajmer Road",
    type: "Showroom",
    address: "Plot No-3, Duleshwar Bag, Ajmer Rd, Jaipur, Rajasthan 302001",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Jaipur",
  },
  {
    title: "NEXA Vipul Motors, Dausa",
    type: "Showroom",
    address: "1228/2, Jaipur Dausa Tiraha, Agra - Jaipur Rd, Dausa, Rajasthan 303303",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Dausa",
  },
  {
    title: "NEXA Vipul Motors, Bikaner, Shri Ganganagar Road",
    type: "Showroom",
    address: "Shop No S1-6, Woolen Mill Industrial Area Rd, Sri Ganganagar Rd, SWM RIICO Residential Colony, Bichhwal, Bikaner, Rajasthan 334006",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Bikaner",
  },
  {
    title: "True Value Vipul Motors, Noida Sector 63",
    type: "True Value",
    address: "J 27, Faridabad - Noida - Ghaziabad Expy, Block J, Sector 63, Noida, Uttar Pradesh 201301",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Noida",
  },
  {
    title: "True Value Vipul Motors, Faridabad, Bata Chowk",
    type: "True Value",
    address: "No.868, PLOT No. B-1/19,B-1/32,B-1/33,B-1/34, (Near Metro Pillar, Mathura Rd, Sector 11, Faridabad, Haryana 121006",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Faridabad",
  },
  {
    title: "True Value Vipul Motors, Jaipur",
    type: "True Value",
    address: "Padmawati Colony-II, opposite of Metro Pillar No 25, Jaipur, Rajasthan 302020",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Jaipur",
  },
  {
    title: "Service Vipul Motors, Noida, Sec-5",
    type: "Workshop",
    address: "PLOT NO. A-111 Sector 5, Noida, Uttar Pradesh 201301",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Noida",
  },
  {
    title: "Service Vipul Motors, Noida, Sec-63",
    type: "Workshop",
    address: "14, Block J, Sector 63, Noida, Chotpur, Uttar Pradesh 201301",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Noida",
  },
  {
    title: "Nexa Service Vipul Motors, Noida, Sec 57",
    type: "Workshop",
    address: "C-1, Block C, Sector 57, Noida, Uttar Pradesh 201301",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Noida",
  },
  {
    title: "Service Vipul Motors ECOTECH-12",
    type: "Workshop",
    address: "Plot No 64 Roza Yakubpur Greater Noida, Uttar Pradesh Greter, Roza Yakubpur, Noida, Uttar Pradesh 201318",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Noida",
  },
  {
    title: "Service Vipul Motors Jhilmil",
    type: "Workshop",
    address: "Metro Station Jhilmil B/ 26, behind of, Jhilmil Industrial Area, Jhilmil Colony, New Delhi, Delhi 110095",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "New Delhi",
  },
  {
    title: "Service Vipul Motors Mathura Road",
    type: "Workshop",
    address: "27/5 KM, NH-19, Faridabad, Haryana 121002",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Faridabad",
  },
  {
    title: "Service Vipul Motors YMCA Faridabad",
    type: "Workshop",
    address: "PLOT NO. 1A,  19/6, NH-19, Indra Nagar, Sector 6, Faridabad, Haryana 121001",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Faridabad",
  },
  {
    title: "Nexa Service Vipul Motors Faridabad Bata Chowk",
    type: "Workshop",
    address: "Bata Chowk, Industrial Plot No 34, Sub Division No-3, New Industrial Township, Faridabad, Haryana 121001",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Faridabad",
  },
  {
    title: "Service Vipul Motors, Gurugram, Udyog Vihar Phase 3",
    type: "Workshop",
    address: "Plot No A504 Phase III, Udyog Vihar, Sector 20, Gurugram, Haryana 122001",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Gurugram",
  },
  {
    title: "Service Vipul Motors Sahrol",
    type: "Workshop",
    address: "36, Sub. Major Laxmi Chand Rd, Sector 18, Gurugram, Sarhol, Haryana 122022",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Gurugram",
  },
  {
    title: "Service Vipul Motors Malvya nagar",
    type: "Workshop",
    address: "AB-1, B-12, Central Road, Malviya Nagar Industrial Area, Malviya Nagar, Jaipur, Rajasthan 302017",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Jaipur",
  },
  {
    title: "Service Vipul Motors Jotwara",
    type: "Workshop",
    address: "29, Jhotwara Industrial Area, Jhotwara, Jaipur, Rajasthan 302012",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Jaipur",
  },
  {
    title: "Nexa Service Vipul Motors Dausa",
    type: "Workshop",
    address: "1365, Jaipur Rd, opp. RTDC Midway, Rajput Colony, RIICO Area, Dausa, Rajasthan 303303",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Dausa",
  },
  {
    title: "Service Vipul Motors Dausa",
    type: "Workshop",
    address: "Agra - Jaipur Rd, Vinayak Nagar, Dausa, Rajasthan 303303",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Dausa",
  },
  {
    title: "Nexa Service Vipul Motors Bikaner",
    type: "Workshop",
    address: "E-62, Bichwal Industrial Area, Bikaner, Rajasthan",
    workingHours: "9:30 AM - 8:00 PM",
    contactNo: "+91 9990057744",
    email: "digitalmanager@vipulmotors.com",
    city: "Bikaner",
  },
];


export const marutiSuzukiModels = [
  "Alto K10",
  "Alto 800",
  "Wagon R",
  "Celerio",
  "Swift",
  "Dzire",
  "Baleno",
  "Fronx",
  "Ignis",
  "Ciaz",
  "XL6",
  "Ertiga",
  "Brezza",
  "Grand Vitara",
  "Jimny",
  "Invicto",
  "S-Presso",
  "Eeco"
];

